services:
  - type: web
    name: e-learning-backend
    env: python
    plan: free

    rootDir: backend

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

    buildCommand: |
      pip install --upgrade pip
      pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt

    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
